MB.Library.Client = MB.Library.Client or {}

include("mb-library/client/ui/mb_ui.lua")
include("mb-library/client/themes/mb_themes.lua")
include("mb-library/client/ui/mb_networking.lua")
include("mb-library/client/ui/mb_admin_panel.lua")
include("mb-library/client/server_info/mb_server_info.lua")
include("mb-library/client/graphics/mb_graphics.lua")
include("mb-library/client/interactive/mb_interactive.lua")
include("mb-library/client/notifications/mb_notifications.lua")
include("mb-library/client/animations/mb_animations.lua")
include("mb-library/client/localization/mb_localization.lua")
include("mb-library/client/settings/mb_settings.lua")
include("mb-library/client/addons/mb_addons.lua")
include("mb-library/client/status/mb_status.lua")
include("mb-library/client/achievements/mb_achievements.lua")
include("mb-library/client/cross_platform/mb_cross_platform.lua")
include("mb-library/client/performance/mb_performance.lua")
include("mb-library/client/chat/mb_chat.lua")
include("mb-library/client/fonts/mb_fonts.lua")
include("mb-library/client/utilities/mb_colors.lua")
include("mb-library/client/demo/mb_demo.lua")

MB.Library.Log("Client module loaded") 